# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='tradePics')),
                ('enter', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stop', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(null=True)),
                ('result', models.TextField(null=True)),
                ('tradeType', models.TextField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
    ]
