# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20170901_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='result',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tradeType',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
