# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20170902_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
