# Generated by Django 2.0.1 on 2018-01-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0002_auto_20180118_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='key',
            field=models.CharField(default='l', max_length=300),
            preserve_default=False,
        ),
    ]
