# Generated by Django 2.0.1 on 2018-01-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0003_auto_20180118_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotificationtoken',
            name='id',
        ),
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='key',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
